Description: fix exception message in Crypo.PublicKey.RSA.generate
Author: Sebastian Ramacher <s.ramacher@gmx.at>
Bug-Debian: http://bugs.debian.org/627959
Last-Update: 2011-05-26

--- python-crypto-2.3.orig/lib/Crypto/PublicKey/RSA.py
+++ python-crypto-2.3/lib/Crypto/PublicKey/RSA.py
@@ -203,8 +203,8 @@ class RSAImplementation(object):
 
     def generate(self, bits, randfunc=None, progress_func=None):
         if bits < 1024 or (bits & 0xff) != 0:
-            # pubkey.getStrongPrime doesn't like anything that's not a multiple of 128 and > 512
-            raise ValueError("RSA modulus length must be a multiple of 256 and > 1024")
+            # pubkey.getStrongPrime doesn't like anything that's not a multiple of 256 and >= 1024
+            raise ValueError("RSA modulus length must be a multiple of 256 and >= 1024")
         rf = self._get_randfunc(randfunc)
         obj = _RSA.generate_py(bits, rf, progress_func)    # TODO: Don't use legacy _RSA module
         key = self._math.rsa_construct(obj.n, obj.e, obj.d, obj.p, obj.q, obj.u)
